# Generated by Django 3.1.3 on 2021-10-30 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_auto_20211029_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 15, 30, 15, 876918)),
        ),
    ]
