# Generated by Django 3.1.3 on 2021-11-01 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_auto_20211030_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 12, 41, 23, 979767)),
        ),
    ]
